easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Auteur
       - App\Entity\Editeur
       - App\Entity\Genre
       - App\Entity\Livre
       - App\Entity\Nationalite
